language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  api_key:
    secure: 0hjgsO+Q6LNoGTgRWLm7vCFZPhjP2uQsA9b5tOZUGF0jmczRXRb/P6wXVXOHdhgsuJqJHFcDX6mk+0/zLqCW/8wj2QvXRYGvGhyUCVc56B/kJYW8Fzjz9VN6mQvHUwgHco9EC50XFoLXL8DHpkOx/9vFvHlKsJyimIPpOjG/0taC6fqJiZegq3vRKKMwUacI/25eHezYuSQEPd9lQ5O5jCsdjhytjXauybQFpb9fmE5JjTycMapLMriTkrlj2JHrsmNa3tWNiVAMRXX3DaeYnMJZeMDIRIPutuX538wpnVB0lI7vdP7EDLyMETrTJZUf0pUkL0ekEPwYiQahR64y+gAkVBdz6SfM7Y1/5gqUE5PjMrp3qClQ8y1Zv9JpqvFm8W5310HBskYryv7gVsPU+GvrtWn6YNf6+63DSkhWsvtFYoZslCO/glVBo1X6LlV0XR28FeV8SOKpbB1lryczfKdjPaWi6ltLQCzYcqWqZmxNoT7JJFBMUz7N7tADGASegAMMdY1jojCaBh2Fc0/tBLTt7vD88Eg4LJlgmFnjftml0BLJLNXEWtFT1hOQyK6HjXGNScrxM+L1+qXneooUeoGSfygjeiWydorhKyPC4RAvvdVW69NbCQsB2m97ujp1oXouAi344WIzQfpyxMo5EAS1t7weUe7WDXrDwkH8fwY=
