language: node_js
node_js: '8'
deploy:
  provider: npm
  email: developer@ridi.com
  api_key:
    secure: RLSvI2y3w4t4wya82H7QrbTx0dw9i/YKdAiiheJEsjyg3oxNpym5ncQviLq4ZqSy4VDN8lX23VDnIw/e1EsWMNw2Sx/YpbqyLYfOctEiEBEVeV/Qe3RR+3mbaWYOsgNHwHWH8Zt7t2pnRUQOtXESxvrbdQTmE/h13ER076ok7p7RBC87MpUHlPExqdK4SSDVOUHbbdkNqdj8gIbNCR/MN9WJZhpVHu0dn7j+OYREwTaU5//X/0m6KCiWX4vQsutjae16aGtDSSgKInDUEa/AdgykZGATgUAPTIOXhtJaPHG6EphvGbhpqjCePp4MKzVSLGL3GKyyD8L1KsojfVOt3m8aRDDqcgjpjQcnwcLm+A9MHjI3PagRqRI+0oEclGFdXu8XJqy9RjgZepUrr7wPUFOu4hNtYHP+izmklrz+x6DQ24bmTh5GN8IgbK3IPKukt+VMtrTY7xXEV90O5HeOaf7YaKKTuAr958q7NW80YkgmDg5e45gj4zj/PhIkIgBH9s2gbLLGfsHrZwaGYfnfklceZ0ZGmj5hyLYCScjPKGzxmCzHhVJwfDlQVrRGeWucESaAg1NN7u89gQ2YQy0KLkIF46I2XXTrXfxYa7efOaSseGQYfb0RJB7gAZLYoTMZ2hWXCQ7/HOt0kwFl4lIVIyWg+fqCtOkpT1Vud+G+sRE=
  on:
    tags: true
